In [ ]:
pip install rasterio

     |████████████████████████████████| 19.3 MB 5.1 MB/s 


In [ ]:
pip install earthpy

     |████████████████████████████████| 1.4 MB 7.8 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 994 kB 36.1 MB/s 
     |████████████████████████████████| 6.6 MB 43.2 MB/s 
     |████████████████████████████████| 15.4 MB 37 kB/s 
  Created wheel for earthpy: filename=earthpy-0.9.2-py3-none-any.whl size=1365096 sha256=0cb9dea2c899362763dc9128daee1cca1aaf144e0a55cdc567e2d9262a607e97
  Stored in directory: /root/.cache/pip/wheels/80/4d/12/9d924aa338ecb211c35e6fff47330e3f6d14b8c74971c527ca
Successfully built earthpy


In [ ]:
## Requirements :

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from osgeo import gdal
import sys
import os
from glob import glob
# To show the image
import rasterio
from rasterio.plot import show
# plot hists
import earthpy.plot as ep
import earthpy as et
import earthpy.spatial as es

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Datasets/Dataset.csv')

In [ ]:
df.head()

date_time  ...                                  Image_name
0  2019-03-31  ...  20190331T112119_20190331T112753_T29TQF.tif
1  2019-04-02  ...  20190402T110621_20190402T110826_T29TQF.tif
2  2019-04-12  ...  20190412T110621_20190412T111313_T29TQF.tif
3  2019-04-10  ...  20190410T112119_20190410T112212_T29TQF.tif
4  2019-04-20  ...  20190420T112119_20190420T112254_T29TQF.tif

[5 rows x 5 columns]

In [ ]:
df.describe()

soil_moisture_depth_0.050000         depth
count                     92.000000  9.200000e+01
mean                       0.129087  5.000000e-02
std                        0.066251  9.069990e-17
min                        0.046000  5.000000e-02
25%                        0.061750  5.000000e-02
50%                        0.130500  5.000000e-02
75%                        0.195250  5.000000e-02
max                        0.259000  5.000000e-02

In [ ]:
df['Image_name'].iloc[0]

'20190331T112119_20190331T112753_T29TQF.tif'

In [ ]:
path = '/content/drive/MyDrive/soilMoisture/Sentinel_images/20190402T110621_20190402T110826_T29TQF.tif'
data = tif_to_matrix(path)
print(data)

[[[ 463  463  463 ...  667  667  667]
  [ 463  463  463 ...  667  667  667]
  [ 463  463  463 ...  667  667  667]
  ...
  [ 751  751  751 ...  591  591  591]
  [ 751  751  751 ...  591  591  591]
  [ 751  751  751 ...  591  591  591]]

 [[ 448  539  654 ...  670  642  599]
  [ 446  630  793 ...  636  641  657]
  [ 468  673  805 ...  615  715  728]
  ...
  [ 830  813  849 ...  583  612  679]
  [ 844  855  880 ...  588  531  631]
  [ 838  919  905 ...  588  542  609]]

 [[ 842  947 1112 ... 1122 1062 1034]
  [ 841 1112 1380 ... 1122 1090 1128]
  [ 890 1178 1412 ... 1078 1130 1204]
  ...
  [1394 1376 1378 ... 1036 1132 1238]
  [1460 1418 1396 ... 1004 1010 1130]
  [1440 1472 1472 ... 1012 1030 1130]]

 ...

 [[4478 4478 4478 ... 3697 3697 3697]
  [4478 4478 4478 ... 3697 3697 3697]
  [4478 4478 4478 ... 3697 3697 3697]
  ...
  [3866 3866 3866 ... 3514 3514 3514]
  [3866 3866 3866 ... 3514 3514 3514]
  [3866 3866 3866 ... 3514 3514 3514]]

 [[2760 2760 3114 ... 3292 3267 3267]
  [2760 2760

In [ ]:
## Read tif image as Array :

def tif_to_matrix(path):
  src_ds = gdal.Open(path)
  data = src_ds.ReadAsArray()
  return data 

In [ ]:
## Normalize bands into 0.0 - 1.0 scale :
def normalize(array):
    array_min, array_max = array.min(), array.max()
    return (array - array_min) / (array_max - array_min)

In [ ]:
def indexes_formula(data):
  L = 0.5
  gndvi = es.normalized_diff(data[7], data[2])
  savi = savi = ((data[7] - data[3]) / (data[7] + data[3] + L)) * (1 + L)
  ndmi = es.normalized_diff(data[7], data[10])
  mndwi = es.normalized_diff(data[2], data[10])
  mndwi = normalize(mndwi)
  return gndvi, savi, ndmi, mndwi

In [ ]:
def savi_formula(data):
  L = 0.5
  savi = ((data[7] - data[3]) / (data[7] + data[3] + L)) * (1 + L)
  return savi

In [ ]:
def ndmi_formula(data):
  ndmi = es.normalized_diff(data[7], data[10])
  return ndmi 

In [ ]:
def mndwi_formula(data):
  mndwi = es.normalized_diff(data[2], data[10])
  return mndwi

In [ ]:
df['soil_moisture_depth_0.050000'].iloc[0]

0.14800000000000002

In [ ]:
L['soil_moisture_depth_0.050000']

0.14800000000000002

In [ ]:
S_bands_1 = glob("/content/drive/MyDrive/soilMoisture/Sentinel_images/*.tif")
S_bands_2 = glob("/content/drive/MyDrive/soilMoisture/Images_test/*.tif")

In [ ]:
S_bands_2[0]

'/content/drive/MyDrive/soilMoisture/Images_test/20200204T112149_20200204T112602_T29TQF.tif'

In [ ]:
directory1 = "/content/drive/MyDrive/soilMoisture/Sentinel_images"  
directory2 = "/content/drive/MyDrive/soilMoisture/Images_test"
Dict = {}
List_images = []
List_SMC = []
list_b = [0,1,4,5,9,10]
for i in range(1,len(df)) :
  List_Nbands = [] 
  list_indexes = []
  img = df['Image_name'].iloc[i]
  SMC = df['soil_moisture_depth_0.050000'].iloc[i]
  path1= directory1 + '/'+ img
  path2 = directory2 + '/'+ img
  if path1 in S_bands_1 :
    data = tif_to_matrix(path1)
  elif path2 in S_bands_2 :
    data = tif_to_matrix(path2)

  for e in list_b :
    band = normalize(data[e])
    List_Nbands.append(band)

  list_indexes = indexes_formula(data)
  for elt in list_indexes :
    List_Nbands.append(elt)

  List_SMC.append(SMC)
  List_images.append(List_Nbands)



Dict['image'] = List_images
Dict['soilreadings'] = List_SMC
   

/usr/local/lib/python3.7/dist-packages/earthpy/spatial.py:105: RuntimeWarning: invalid value encountered in true_divide
  n_diff = (b1 - b2) / (b1 + b2)


In [ ]:
df_bands = pd.DataFrame(List_images,columns=['B1','B2','B5','B6','B9','B10','GNDVI','SAVI','NDMI','MNDWI'])

In [ ]:
df_bands['soil_moisture'] = List_SMC

In [ ]:
df_bands.head()

B1  ... soil_moisture
0  [[0.0, 0.0, 0.0, 0.0, 0.14583333333333334, 0.1...  ...         0.146
1  [[0.046703296703296704, 0.046703296703296704, ...  ...         0.149
2  [[0.175, 0.175, 0.175, 0.175, 0.21919642857142...  ...         0.135
3  [[0.4496021220159151, 0.4496021220159151, 0.44...  ...         0.214
4  [[0.0, 0.0, 0.0, 0.0, 0.016065830721003135, 0....  ...         0.141

[5 rows x 11 columns]

In [ ]:
df_bands.to_csv ('Dataset_bands&indexes.csv', header=True, index=False)